# Generated by Django 4.2.27 on 2026-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashback_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cashback_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='has_cashback',
            field=models.BooleanField(default=False),
        ),
    ]
