# Generated by Django 4.2.27 on 2026-02-02 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('secondary', 'Gray'), ('dark', 'Dark')], default='primary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SIPInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=200)),
                ('folio_number', models.CharField(blank=True, max_length=100)),
                ('scheme_type', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('HYBRID', 'Hybrid'), ('INDEX', 'Index Fund'), ('ELSS', 'ELSS (Tax Saver)'), ('LIQUID', 'Liquid Fund')], default='EQUITY', max_length=20)),
                ('amount_per_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=15)),
                ('start_date', models.DateField()),
                ('current_units', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('current_nav', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='expenses.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag'),
        ),
        migrations.AddConstraint(
            model_name='sipinvestment',
            constraint=models.UniqueConstraint(fields=('user', 'fund_name', 'folio_number'), name='unique_sip'),
        ),
        migrations.AddConstraint(
            model_name='filterpreset',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_filter_preset'),
        ),
    ]
