# Generated by Django 4.2.27 on 2026-01-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_participant_sharedexpense_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='expenses.participant'),
        ),
    ]
