# Generated by Django 4.2.27 on 2026-02-02 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_tag_sipinvestment_filterpreset_expense_tags_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sipinvestment',
            name='unique_sip',
        ),
        migrations.RemoveField(
            model_name='sipinvestment',
            name='current_nav',
        ),
        migrations.RemoveField(
            model_name='sipinvestment',
            name='current_units',
        ),
        migrations.RemoveField(
            model_name='sipinvestment',
            name='folio_number',
        ),
        migrations.RemoveField(
            model_name='sipinvestment',
            name='scheme_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='sip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.sipinvestment'),
        ),
        migrations.AddField(
            model_name='sipinvestment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category'),
        ),
        migrations.AddField(
            model_name='sipinvestment',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipinvestment',
            name='sip_day',
            field=models.PositiveIntegerField(default=1, help_text='Day of month for SIP deduction (1-28)'),
        ),
        migrations.AddConstraint(
            model_name='sipinvestment',
            constraint=models.UniqueConstraint(fields=('user', 'fund_name'), name='unique_sip'),
        ),
    ]
