# Generated by Django 4.2.27 on 2026-02-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_expense_expenses_ex_user_id_207090_idx_and_more'),
        ('expenses', '0016_remove_sipinvestment_unique_sip_and_more'),
    ]

    operations = [
    ]
