# Generated by Django 4.2.27 on 2026-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_allow_shared_expense_deletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedexpense',
            name='payer',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_payer',
            field=models.BooleanField(default=False),
        ),
    ]
