# Generated by Django 4.2.27 on 2026-01-19 18:17

from django.db import migrations, models
import django.db.models.deletion


def migrate_participants_to_friends(apps, schema_editor):
    """
    Migrate existing Participant records to Friend + SharedExpenseParticipant.
    """
    Participant = apps.get_model('expenses', 'Participant')
    Friend = apps.get_model('expenses', 'Friend')
    SharedExpenseParticipant = apps.get_model('expenses', 'SharedExpenseParticipant')
    Share = apps.get_model('expenses', 'Share')

    # Get all unique participant names (excluding user participants)
    unique_names = Participant.objects.filter(is_user=False).values_list('name', flat=True).distinct()

    # Create Friend records for each unique name
    friend_map = {}
    for name in unique_names:
        name = name.strip() if name else ''
        if name and name not in friend_map:
            friend, created = Friend.objects.get_or_create(name=name)
            friend_map[name] = friend

    # Migrate each Participant to SharedExpenseParticipant
    participant_id_map = {}  # Maps old participant id to new SharedExpenseParticipant
    for old_participant in Participant.objects.all():
        friend = None
        if not old_participant.is_user:
            name = old_participant.name.strip() if old_participant.name else ''
            friend = friend_map.get(name)

        new_participant = SharedExpenseParticipant.objects.create(
            shared_expense=old_participant.shared_expense,
            friend=friend,
            is_user=old_participant.is_user,
            is_payer=old_participant.is_payer
        )
        participant_id_map[old_participant.id] = new_participant

    # Update Share records to point to new SharedExpenseParticipant
    for share in Share.objects.all():
        old_participant_id = share.participant_id
        if old_participant_id in participant_id_map:
            share.new_participant = participant_id_map[old_participant_id]
            share.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - convert SharedExpenseParticipant back to Participant.
    """
    # This is a destructive reverse - we'll lose the Friend master table linkage
    SharedExpenseParticipant = apps.get_model('expenses', 'SharedExpenseParticipant')
    Participant = apps.get_model('expenses', 'Participant')
    Share = apps.get_model('expenses', 'Share')

    participant_id_map = {}
    for sep in SharedExpenseParticipant.objects.all():
        name = "You" if sep.is_user else (sep.friend.name if sep.friend else "Unknown")
        old_participant = Participant.objects.create(
            shared_expense=sep.shared_expense,
            name=name,
            is_user=sep.is_user,
            is_payer=sep.is_payer
        )
        participant_id_map[sep.id] = old_participant

    # Update Share records
    for share in Share.objects.all():
        if share.new_participant_id in participant_id_map:
            share.participant = participant_id_map[share.new_participant_id]
            share.save()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_remove_payer_fk_add_is_payer'),
    ]

    operations = [
        # Step 1: Create Friend model
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Step 2: Create SharedExpenseParticipant model (with different related_name temporarily)
        migrations.CreateModel(
            name='SharedExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=False)),
                ('is_payer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_participations', to='expenses.friend')),
                ('shared_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_participants', to='expenses.sharedexpense')),
            ],
        ),
        # Step 3: Add temporary field to Share to hold new participant reference
        migrations.AddField(
            model_name='share',
            name='new_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_shares', to='expenses.sharedexpenseparticipant'),
        ),
        # Step 4: Run data migration
        migrations.RunPython(migrate_participants_to_friends, reverse_migration),
        # Step 4.5: Remove constraint on old participant field
        migrations.RemoveConstraint(
            model_name='share',
            name='unique_share_per_participant',
        ),
        # Step 5: Remove old participant field from Share
        migrations.RemoveField(
            model_name='share',
            name='participant',
        ),
        # Step 6: Rename new_participant to participant
        migrations.RenameField(
            model_name='share',
            old_name='new_participant',
            new_name='participant',
        ),
        # Step 7: Make participant non-nullable
        migrations.AlterField(
            model_name='share',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.sharedexpenseparticipant'),
        ),
        # Step 8: Delete old Participant model
        migrations.DeleteModel(
            name='Participant',
        ),
        # Step 9: Update SharedExpenseParticipant related_name
        migrations.AlterField(
            model_name='sharedexpenseparticipant',
            name='shared_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.sharedexpense'),
        ),
        # Step 10: Add constraints
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('friend__isnull', False)), fields=('shared_expense', 'friend'), name='unique_friend_per_shared_expense'),
        ),
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_user', True)), fields=('shared_expense', 'is_user'), name='unique_user_per_shared_expense'),
        ),
        # Step 11: Re-add constraint on Share (new participant)
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('shared_expense', 'participant'), name='unique_share_per_participant'),
        ),
    ]
