# Generated by Django 4.2.27 on 2026-05-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0046_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Loan Name')),
                ('loan_type', models.CharField(choices=[('HOME', 'Home Loan'), ('CAR', 'Car Loan'), ('PERSONAL', 'Personal Loan'), ('EDUCATION', 'Education Loan'), ('BUSINESS', 'Business Loan'), ('OTHER', 'Other')], default='HOME', max_length=20, verbose_name='Loan Type')),
                ('initial_principal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Initial Principal Amount')),
                ('duration_months', models.IntegerField(verbose_name='Duration (Months)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount Paid (EMI)')),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Portion')),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest Portion')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='expenses.account', verbose_name='Paid From Account')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='expenses.loan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LoanInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Annual Interest Rate (%)')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rates', to='expenses.loan')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
