# Generated by Django 4.2.27 on 2026-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0047_loan_loanrepayment_loaninterestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount in Base Currency'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Exchange Rate'),
        ),
    ]
