# Generated by Django 4.2.27 on 2026-05-16 13:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0049_transfer_accounts_must_differ'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('source_id', models.BigIntegerField()),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=20)),
                ('currency', models.CharField(blank=True, choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], max_length=5)),
                ('fx_rate_to_base', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=15)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='expenses.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.journalentry')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='expenses.ledgeraccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['user', 'account_type'], name='expenses_le_user_id_4c58a7_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['is_active'], name='expenses_le_is_acti_2efd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['ledger_account', 'journal_entry'], name='expenses_jo_ledger__4e449f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account_ref'], name='expenses_jo_account_8fe68f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'posted_at'], name='expenses_jo_user_id_300587_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='expenses_jo_source__eacc52_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='expenses_jo_status_7507d2_idx'),
        ),
    ]
