# Generated by Django 4.2.27 on 2026-05-16 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0050_journalentry_ledgeraccount_journalline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerPostingFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('source_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETRYING', 'Retrying'), ('RESOLVED', 'Resolved'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='expenses_le_status_2dcf6f_idx'), models.Index(fields=['source_type', 'source_id'], name='expenses_le_source__ab6ffe_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ledger_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('drift_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('MATCH', 'Match'), ('DRIFT', 'Drift')], max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_reconciliation_reports', to='expenses.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_reconciliation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'as_of_date'], name='expenses_le_user_id_c2e4de_idx'), models.Index(fields=['account', 'as_of_date'], name='expenses_le_account_680d16_idx'), models.Index(fields=['status'], name='expenses_le_status_6f7b89_idx')],
            },
        ),
    ]
